[tool.poetry]
name = "Reservation-app"
version = "0.1.0"
description = "Reservation app for whole house/flat."
authors = ["wojtiwojt"]

[tool.poetry.dependencies]
python = "3.8.10"
django = "3.*"
djangorestframework = "3.*"
django-filter = "2.*"

[tool.poetry.dev-dependencies]
